import {useEffect,useMemo,useState} from 'react';
import {useWorkbench} from '../app/workbench';
import FeatureGuide from '../components/FeatureGuide';
import Page from '../components/Page';
import {compileExperience,devices,parseExperience,type ExperienceDefinition,type InputMode,type OutputMode,type TaskKind} from '../core';

export default function Compiler(){
 const work=useWorkbench();const [text,setText]=useState(work.experience.prompt);const [draft,setDraft]=useState<ExperienceDefinition|null>(work.experience);const [messages,setMessages]=useState<string[]>([]);const [saved,setSaved]=useState(false);
 useEffect(()=>{const timer=setTimeout(()=>{const parsed=parseExperience(text);setDraft(parsed.experience);setMessages([...parsed.errors,...parsed.warnings]);setSaved(false)},220);return()=>clearTimeout(timer)},[text]);
 const plans=useMemo(()=>draft?devices.map(device=>compileExperience(draft,device)):[],[draft]);
 const update=<K extends keyof ExperienceDefinition>(key:K,value:ExperienceDefinition[K])=>{if(!draft)return;setDraft({...draft,[key]:value});setSaved(false)};
 const useInLab=()=>{if(!draft)return;work.setExperience({...draft,id:`custom-${Date.now()}`,name:draft.name||'Custom experience'});setSaved(true)};
 return <Page index="03" eyebrow="EXPERIENCE COMPILER / LIVE CROSS-DEVICE PLAN" title={<>Type an idea.<br/><em>Watch it become a system.</em></>} lead="For designers and developers translating a product idea into explicit inputs, processing, outputs, fallbacks and device requirements. The plan updates while you type.">
  <FeatureGuide title="What the compiler actually does" intro="It does not pretend to generate deployable AI code. It converts a supported sentence into a structured contract, evaluates that contract against every device, and sends the chosen version into Lens Lab." steps={[
   {number:'1',title:'Describe one behavior',body:'Try translation, scene description, live captions, or a reminder.'},
   {number:'2',title:'Review the detected contract',body:'Correct the input, task, output order, language, and privacy controls.'},
   {number:'3',title:'Use it in Lens Lab',body:'The saved custom experience becomes the simulator’s active experience.'},
  ]}/>
  <div className="compiler-workspace">
   <section className="author-panel panel-dark"><div className="panel-title"><span>YOUR IDEA</span><b className={draft?'valid':'invalid'}>{draft?'LIVE PLAN READY':'NEEDS REVISION'}</b></div><label>Describe the experience<textarea value={text} onChange={e=>setText(e.target.value)} placeholder="When I see a sign, translate it into Spanish…"/><small className="field-help">The panel on the right updates about 0.2 seconds after you type.</small></label><div className="prompt-suggestions"><button onClick={()=>setText('When I see a sign, translate it into Spanish. Show it on the display; if there is no display, speak it aloud.')}>Translate a sign</button><button onClick={()=>setText('Caption speech from the microphone and show it on the display.')}>Caption a conversation</button><button onClick={()=>setText('Describe the camera scene and speak the result aloud.')}>Describe a scene</button></div>{messages.map((message,i)=><p className={draft?'compiler-message':'compiler-message error'} key={`${message}-${i}`}>{message}</p>)}</section>
   <section className="ir-panel"><header><div><p className="eyebrow">DETECTED EXPERIENCE</p><h2>{draft?.name??'No supported plan yet'}</h2></div><span className={`truth-label ${draft?'simulated':'unavailable'}`}>{draft?'UPDATES LIVE':'INVALID'}</span></header>{draft?<><div className="structured-controls"><label>Input<select value={draft.input} onChange={e=>update('input',e.target.value as InputMode)}><option value="camera">Camera</option><option value="microphone">Microphone</option><option value="manual">Manual trigger</option></select></label><label>Task<select value={draft.task} onChange={e=>update('task',e.target.value as TaskKind)}><option value="translate">Translate</option><option value="describe">Describe</option><option value="caption">Caption</option><option value="notify">Notify</option></select></label><label>Primary output<select value={draft.preferredOutputs[0]} onChange={e=>update('preferredOutputs',[e.target.value as OutputMode,...draft.preferredOutputs.filter(item=>item!==e.target.value)])}><option value="display">Display</option><option value="audio">Audio</option></select></label><label>Language<input value={draft.language} onChange={e=>update('language',e.target.value)}/></label></div><div className="pipeline-graph"><div><span>INPUT</span><strong>{draft.input}</strong></div><i>→</i><div><span>PROCESS</span><strong>{draft.task}</strong></div><i>→</i>{draft.preferredOutputs.map((output,i)=><div key={output}><span>{i?'FALLBACK':'OUTPUT'}</span><strong>{output}</strong></div>)}</div><div className="compiler-save"><button className="button primary" onClick={useInLab}>{saved?'Saved to Lens Lab ✓':'Use this in Lens Lab'}</button>{saved&&<a className="button" href="#/lab">Open Lens Lab →</a>}<span>{draft.privacy==='local-only'?'Local-only processing requested':'Provider processing permitted'}</span></div><details><summary>Show generated JSON contract</summary><pre className="code-block">{JSON.stringify(draft,null,2)}</pre></details></>:<div className="empty-state">Try one of the examples or write a single translate, describe, caption, or reminder behavior.</div>}</section>
  </div>
  {draft&&<section className="compile-matrix"><header><div><p className="eyebrow">DEVICE COMPATIBILITY / LIVE</p><h2>{devices.length} profiles evaluated</h2></div><span>Click a runnable row to open it in Lens Lab</span></header>{plans.map(plan=><a href={`#/lab?device=${plan.deviceId}`} className="compile-row" key={plan.deviceId}><div><strong>{plan.deviceName}</strong><small>{plan.adapterId??'RESEARCH PROFILE — NO OPENLENS ADAPTER'}</small></div><span title={plan.steps[0].reason}>{plan.steps[0].route}</span><i>→</i><span title={plan.steps[1].reason}>{plan.steps[1].route}</span><i>→</i><span title={plan.steps[2].reason}>{plan.steps[2].route}</span><b className={`compatibility ${plan.compatibility}`}>{plan.compatibility}</b></a>)}</section>}
 </Page>;
}
