import {useMemo,useState} from 'react';
import FeatureGuide from '../components/FeatureGuide';
import Page from '../components/Page';
import DeviceFitEngine from '../components/DeviceFitEngine';
import DeviceDoctor from '../components/DeviceDoctor';
import DeviceCapabilityMatrix from '../components/DeviceCapabilityMatrix';
import '../device-matrix.css';
import {capabilityKeys,formatSpecification,getDevice,specificationKeys,specificationLabels} from '../core';
import {devices} from '../data/devices';

export default function Devices(){
 const [query,setQuery]=useState('');
 const jumpTo=(id:string)=>{const target=document.getElementById(id);target?.focus({preventScroll:true});target?.scrollIntoView({block:'start',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})};
 const [selected,setSelected]=useState<string[]>(['openlens-twin','snap-spectacles-2024']);
 const [differences,setDifferences]=useState(false);
 const [doctorId,setDoctorId]=useState<string|null>(null);
 const filtered=devices.filter(d=>`${d.name} ${d.manufacturer} ${d.summary} ${Object.keys(d.capabilities).join(' ')} ${Object.values(d.specifications).map(value=>value.value).join(' ')}`.toLowerCase().includes(query.toLowerCase()));
 const compare=devices.filter(d=>selected.includes(d.id));
 const rows=useMemo(()=>capabilityKeys.filter(key=>!differences||new Set(compare.map(d=>`${d.capabilities[key].physical}/${d.capabilities[key].manufacturerAccess}`)).size>1),[compare,differences]);
 const specRows=useMemo(()=>specificationKeys.filter(key=>!differences||new Set(compare.map(d=>String(d.specifications[key].value))).size>1),[compare,differences]);
 const toggle=(id:string)=>setSelected(current=>current.includes(id)?current.filter(v=>v!==id):current.length<3?[...current,id]:[...current.slice(1),id]);
 return <Page className="instrument-page devices-page" index="02" eyebrow="DEVICE UNIVERSE / 8 SOURCED PROFILES" title={<>The device <em>field guide.</em></>} lead="Eight perspectives on spatial computing. Explore the hardware, compare the constraints, and follow the evidence." actions={<button className="button" onClick={()=>jumpTo('device-fit')}>Find your fit ↗</button>}>
  {doctorId&&<DeviceDoctor device={getDevice(doctorId)} onClose={()=>setDoctorId(null)}/>} 
  <DeviceCapabilityMatrix devices={devices} selected={selected} onToggle={toggle} onInspect={setDoctorId}/>
  <section className="catalog-section" aria-labelledby="catalog-title">
   <header className="catalog-section-head"><div><p className="eyebrow">DEVICE CATALOG</p><h2 id="catalog-title">Inspect the field directly.</h2></div><p>Eight initial profiles. Source depth will continue expanding; unknown stays unknown until evidence exists.</p></header>
   <div className="catalog-tools"><input className="search-input" value={query} onChange={e=>setQuery(e.target.value)} aria-label="Search device catalog" placeholder="Search the field…"/><span className="result-count">{filtered.length} OF {devices.length} PROFILES</span><label className="toggle"><input type="checkbox" checked={differences} onChange={e=>setDifferences(e.target.checked)}/><span/>Show differences only</label></div>
   <div className="device-catalog">{filtered.map((device,index)=><article className={`device-record ${selected.includes(device.id)?'selected':''} device-${index%4}`} key={device.id}>
    <button className="compare-toggle" onClick={()=>toggle(device.id)} aria-pressed={selected.includes(device.id)}>{selected.includes(device.id)?'✓ COMPARING':'＋ COMPARE'}</button>
    <div className="device-number" aria-hidden="true">{String(devices.indexOf(device)+1).padStart(2,'0')}<span>{device.kind==='digital-twin'?'VIRTUAL':'HARDWARE'}</span></div>
    <div className="device-info"><div><p className="eyebrow">{device.manufacturer}</p><h2>{device.name}</h2></div><span className={`truth-label ${device.integrationStatus}`}>{device.integrationStatus.replaceAll('-',' ')}</span><p>{device.summary}</p><div className="device-meta"><span><small>FIELD OF VIEW</small>{device.capabilities.display.physical==='present'?(device.optics.horizontalFovDegrees?.value?`${device.optics.horizontalFovDegrees.value}° ${device.optics.fovAxis??''} FOV`:'FOV UNKNOWN'):'NO DISPLAY'}</span><span><small>MASS</small><b>{formatSpecification('massGrams',device.specifications.massGrams).toUpperCase()}</b></span><span><small>DISPLAY</small><b>{formatSpecification('displayResolution',device.specifications.displayResolution).toUpperCase()}</b></span><span><small>SPECIFICATION COVERAGE</small>{Object.values(device.specifications).filter(value=>value.value!==null).length}/8 SPECS KNOWN</span><span><small>EVIDENCE</small>{device.sources.length} PRIMARY SOURCES</span></div><div className="button-row"><button className="button" type="button" onClick={()=>setDoctorId(device.id)}>Device Doctor</button><a className="text-link" href={device.kind==='digital-twin'?`#/lab?device=${device.id}`:`#/research?device=${device.id}`}>{device.kind==='digital-twin'?'Run this twin →':'Inspect evidence →'}</a></div></div>
   </article>)}</div>
  </section>
  <div className="catalog-jump"><span>{selected.length} profiles in your comparison</span><button onClick={()=>jumpTo('device-comparison')} className="text-link">Compare specifications ↓</button></div>
  <section id="device-comparison" tabIndex={-1} className="compare-table"><header><div><p className="eyebrow">LIVE COMPARISON</p><h2>{compare.length} profiles selected</h2></div><span>Specifications / physical capability / maker API / OpenLens status</span></header>{compare.length?<div className="table-scroll" tabIndex={0} role="region" aria-label="Scrollable device comparison"><table><thead><tr><th>Claim</th>{compare.map(d=><th key={d.id}>{d.name}<small>{d.integrationStatus}</small></th>)}</tr></thead><tbody><tr className="table-section-label"><th colSpan={compare.length+1}>Physical specifications</th></tr><tr><th>Field of view</th>{compare.map(d=>{const value=d.optics.horizontalFovDegrees;return <td className={!value?.value?'unknown-value':''} key={d.id}><b>{d.capabilities.display.physical==='absent'?'No display':value?.value?`${value.value}° ${d.optics.fovAxis==='diagonal'?'diagonal':d.optics.fovAxis==='horizontal'?'horizontal':'axis unknown'}`:'Unknown'}</b><small>{value?.status.replaceAll('-',' ')??'unknown'}</small><p>{value?.note??'No current first-party field-of-view value is recorded.'}</p></td>})}</tr>{specRows.map(key=><tr key={key}><th>{specificationLabels[key]}</th>{compare.map(d=>{const value=d.specifications[key];return <td className={value.value===null?'unknown-value':''} key={d.id}><b>{formatSpecification(key,value)}</b><small>{value.status.replaceAll('-',' ')}</small><p>{value.note}</p>{value.conflicts?.map(conflict=><mark key={String(conflict.value)}>Conflict: {formatSpecification(key,{...value,value:conflict.value})}</mark>)}</td>})}</tr>)}<tr className="table-section-label"><th colSpan={compare.length+1}>Capability and access</th></tr>{rows.map(key=><tr key={key}><th>{key}</th>{compare.map(d=><td key={d.id}><b>{d.capabilities[key].physical}</b><small>{d.capabilities[key].manufacturerAccess}</small><p>{d.capabilities[key].note}</p></td>)}</tr>)}<tr><th>OpenLens execution</th>{compare.map(d=><td key={d.id}><b>{d.kind==='digital-twin'?'Runnable now':'Not connected'}</b><small>{d.kind==='research'?'research and comparison only':'registered deterministic twin'}</small></td>)}</tr></tbody></table></div>:<div className="empty-state">Select devices above to build a comparison.</div>}</section>
  <section id="device-fit" tabIndex={-1}><DeviceFitEngine onInspect={setDoctorId}/></section>
  <details className="lab-guide"><summary>How to read device claims</summary>  <FeatureGuide title="How to use the Device Universe" intro="A device listing answers three separate questions: does the hardware exist, does its maker expose an API, and has OpenLens implemented that API?" steps={[{number:'1',title:'Ask for what you need',body:'Use the Fit Engine to mark capabilities as preferred or required.'},{number:'2',title:'Diagnose the result',body:'Device Doctor separates hardware, maker access and OpenLens execution.'},{number:'3',title:'Compare the finalists',body:'Select up to three profiles and inspect only the differences that matter.'}]}/>

</details>
 </Page>
}
