import {lazy,Suspense,useState} from 'react';
import {useWorkbench} from '../app/workbench';
import FeatureGuide from '../components/FeatureGuide';
import FixtureScene from '../components/FixtureScene';
import Page from '../components/Page';
import TraceViewer from '../components/TraceViewer';
import SimulationControls from '../components/SimulationControls';
import RunPlayback from '../components/RunPlayback';
import VirtualWorldScene from '../components/VirtualWorldScene';
import {assessEnvironment,defaultEnvironment,defaultSimulationConfig,experiencePresets,getDevice,type FailureMode,type SimulationConfig} from '../core';
import {devices,simulationDevices} from '../data/devices';
const LocalAI=lazy(()=>import('../components/LocalAI'));

const scenarios:Array<{id:string;name:string;description:string;experienceId?:string;change:Partial<SimulationConfig>}>= [
 {id:'clean',name:'Park sign translation',description:'Focus a French wayfinding sign and render its Spanish equivalent.',experienceId:'translate-sign',change:{fixture:'street-sign',failureMode:'none',battery:84,network:'online',permission:'granted',environment:{illuminationLux:1200,headMotionDps:6,ambientNoiseDb:35}}},
 {id:'captions',name:'Conversation captions',description:'Detect two park visitors and place their words in the display plane.',experienceId:'live-captions',change:{fixture:'conversation',failureMode:'none',battery:76,network:'online',permission:'granted',environment:{illuminationLux:900,headMotionDps:12,ambientNoiseDb:64}}},
 {id:'guide',name:'Historic garden guide',description:'Describe the visible landmark and path through an audio route.',experienceId:'describe-scene',change:{fixture:'museum-label',failureMode:'none',battery:68,network:'online',permission:'granted',environment:{illuminationLux:480,headMotionDps:4,ambientNoiseDb:32}}},
 {id:'reminder',name:'Quiet park reminder',description:'Trigger a local reminder without camera or microphone acquisition.',experienceId:'quiet-reminder',change:{fixture:'street-sign',failureMode:'none',battery:52,network:'online',permission:'granted',environment:{illuminationLux:120,headMotionDps:0,ambientNoiseDb:24}}},
 {id:'denied',name:'Permission denied',description:'Camera access fails before any image leaves the input stage.',experienceId:'translate-sign',change:{fixture:'street-sign',failureMode:'permission',permission:'denied'}},
 {id:'train',name:'Degraded commute',description:'Noisy conversation and a degraded link add visible route pressure.',experienceId:'live-captions',change:{fixture:'conversation',failureMode:'none',network:'degraded',permission:'granted',environment:{illuminationLux:340,headMotionDps:34,ambientNoiseDb:78}}},
 {id:'power',name:'Critical battery',description:'The twin stops at its safety threshold before starting the experience.',change:{fixture:'museum-label',failureMode:'low-battery',battery:3,permission:'granted'}},
 {id:'offline',name:'Network loss',description:'Inject a lost route and verify the failure appears in the canonical trace.',change:{fixture:'museum-label',failureMode:'network-loss',network:'offline',permission:'granted'}},
];

export default function Lab(){
 const work=useWorkbench();
 const [aiOpen,setAiOpen]=useState(false);
 const [viewMode,setViewMode]=useState<'world'|'diagnostic'>('world');
 const scenarioId=scenarios.find(s=>(!s.experienceId||work.experience.id===s.experienceId)&&Object.entries(s.change).every(([key,value])=>JSON.stringify(work.config[key as keyof SimulationConfig])===JSON.stringify(value)))?.id;
 const device=getDevice(work.deviceId);const plan=work.plan;const fov=device.optics.horizontalFovDegrees;
 const fovWidth=Math.max(44,Math.min(82,46+((fov?.value??30)/70)*32));
 const assessment=assessEnvironment(work.experience.input,plan.steps.at(-1)?.capability,work.config.environment??defaultEnvironment);
 const update=<K extends keyof SimulationConfig>(key:K,value:SimulationConfig[K])=>work.setConfig({...work.config,[key]:value});
 const chooseScenario=(id:string)=>{const scenario=scenarios.find(item=>item.id===id)!;if(scenario.experienceId){const experience=experiencePresets.find(item=>item.id===scenario.experienceId);if(experience)work.setExperience(experience)}work.setConfig({...work.config,battery:defaultSimulationConfig.battery,network:defaultSimulationConfig.network,permission:defaultSimulationConfig.permission,failureRate:0,...scenario.change})};
 const runScenario=()=>{if(device.kind!=='research')work.runCurrent()};
 return <Page className="instrument-page lab-page" index="01" eyebrow="LENS LAB / INTERACTIVE DIGITAL TWIN" title={<>The optical <em>workbench.</em></>} lead="Put an idea in the frame. Change the conditions. Inspect what happens." actions={<div className="instrument-status"><span className="live-dot"/> LOCAL SIMULATION<span>Seeded · repeatable · inspectable</span></div>}>
  <nav className="workspace-tabs"><a className="active" href="#/lab">1. Run</a><a href="#/compiler">2. Create experience</a><a href="#/benchmarks">3. Benchmark</a><a href="#/research">4. Verify claims</a></nav>
  <div className="workbench-grid">
   <aside className="workbench-rail panel-dark"><div className="panel-title"><span>YOUR TEST</span><b>EDITABLE</b></div>
    <button className="button primary full run-button" disabled={device.kind==='research'} onClick={runScenario}>{work.run?'Run again':'Run this scenario'} <span>→</span></button>
    <label>Simulated device<select value={work.deviceId} onChange={e=>work.setDeviceId(e.target.value)}>{[...simulationDevices,...devices.filter(d=>d.kind==='research')].map(d=><option value={d.id} key={d.id}>{d.name}{d.kind==='research'?' — research only':''}</option>)}</select><small className="field-help">Choose the reference twin or a capability model. Hardware profiles remain research-only.</small></label>
    {device.kind==='research'&&<div className="integrity-callout"><strong>THIS PROFILE CANNOT RUN</strong><p>No OpenLens hardware adapter exists. Switch to the Optical Twin while retaining this experience.</p><button onClick={()=>work.setDeviceId('openlens-twin')}>Use Optical Twin now</button></div>}
    <label>Experience<select value={work.experience.id} onChange={e=>work.setExperience(experiencePresets.find(p=>p.id===e.target.value)??work.experience)}>{experiencePresets.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}{!experiencePresets.some(p=>p.id===work.experience.id)&&<option value={work.experience.id}>{work.experience.name} — custom</option>}</select><small className="field-help">{work.experience.prompt}</small></label>
    <div className="control-pair"><label>Repeatable seed<input type="number" value={work.config.seed} min="0" onChange={e=>update('seed',Math.max(0,Math.min(4294967295,Math.trunc(Number(e.target.value)||0))))}/></label><label>Battery %<input type="number" value={work.config.battery} min="0" max="100" onChange={e=>update('battery',Math.max(0,Math.min(100,Number(e.target.value)||0)))}/></label></div>
    <label>Virtual environment<select value={work.config.fixture} onChange={e=>update('fixture',e.target.value as SimulationConfig['fixture'])}><option value="street-sign">Park wayfinding: SORTIE</option><option value="conversation">Park conversation</option><option value="museum-label">Historic garden label</option></select></label>
    <label>Injected failure<select value={work.config.failureMode} onChange={e=>update('failureMode',e.target.value as FailureMode)}><option value="none">No injected failure</option><option value="permission">Permission denied</option><option value="disconnect">Output bridge disconnect</option><option value="timeout">Processing timeout</option><option value="low-battery">Critical battery</option><option value="network-loss">Network loss</option><option value="model-unavailable">Model unavailable</option></select></label>

   </aside>
   <div className="instrument-main"><section className="optical-console"><header><div><span className="live-dot"/>SIMULATION / {device.name.toUpperCase()}</div><div className="scene-actions"><div className="scene-mode-switch" role="group" aria-label="Simulation view"><button aria-pressed={viewMode==='world'} onClick={()=>setViewMode('world')}>Virtual world</button><button aria-pressed={viewMode==='diagnostic'} onClick={()=>setViewMode('diagnostic')}>Diagnostic</button></div><button className="scene-run" disabled={device.kind==='research'} onClick={runScenario}>Run simulation ↗</button></div></header><div className={`optical-view view-${viewMode} ${work.run?.status??''}`}>{viewMode==='world'?<VirtualWorldScene fixture={work.config.fixture} environment={work.config.environment??defaultEnvironment} task={work.experience.task} output={work.run?.output} status={work.run?.status} failureMode={work.config.failureMode} canRun={device.kind!=='research'} onRun={runScenario}/>:<FixtureScene fixture={work.config.fixture} environment={work.config.environment??defaultEnvironment}/>}<div className={`quality-gauge ${assessment.grade}`}><span>SYNTHETIC SIGNAL</span><strong>{assessment.score}/100</strong><i><b style={{width:`${assessment.score}%`}}/></i></div>{fov&&device.capabilities.display.physical==='present'?<div className="fov-frame" style={{'--fov-width':`${fovWidth}%`} as React.CSSProperties}><i/><span>{fov.value}° {device.optics.fovAxis==='horizontal'?'H-FOV':device.optics.fovAxis==='diagonal'?'D-FOV':'FOV (axis unknown)'}</span><small>DISPLAY BOUNDARY</small></div>:<div className="no-display">NO DISPLAY PLANE<br/><small>This profile would need audio or companion output.</small></div>} {viewMode==='diagnostic'&&<div className="lab-hud"><span>{work.experience.task.toUpperCase()} / {work.config.fixture.replace('-',' ').toUpperCase()}</span><strong aria-live="polite">{work.run?(work.run.output??(work.run.status==='failed'?'The run stopped.':'The plan is blocked.')):'Ready when you are.'}</strong><small>{work.run?`${work.run.status.toUpperCase()} · ${work.run.totalMs} MS · SEED ${work.run.seed}`:'RUN THE SCENARIO TO GENERATE OUTPUT'}</small></div>}<div className="view-meta"><span>{viewMode==='world'?'VIRTUAL ENVIRONMENT · GENERATED SCENE':device.integrationStatus.toUpperCase()}</span><span>{work.experience.privacy.replace('-',' ').toUpperCase()}</span></div></div><div className="compile-strip">{plan.steps.map((step,index)=><div key={step.id} data-status={work.run?.trace.find(event=>event.stage===step.stage&&event.status!=='info')?.status??'pending'}><span>{index+1}. {step.stage}</span><strong>{step.route}</strong><small>{work.run?(work.run.trace.find(event=>event.stage===step.stage&&event.status!=='info')?.status??'not reached'):'planned'}</small></div>)}<b className={`compatibility ${plan.compatibility}`}>{plan.compatibility}</b></div></section>
   <aside className="inspector panel-dark"><div className="panel-title"><span>WHAT WILL HAPPEN</span><b>PLAN</b></div>{plan.steps.map((step,index)=><div className="plain-step" key={step.id}><span>{index+1}</span><div><strong>{step.label}</strong><p>{step.reason}</p></div></div>)}<button className="button ghost full" onClick={()=>setAiOpen(v=>!v)}>{aiOpen?'Close local OCR':'Try real local OCR'}</button></aside></div>
  </div>
  {work.run&&<section className={`outcome-card ${work.run.status}`}><div><p className="eyebrow">RUN OUTCOME</p><h2>{work.run.status==='success'?'The experience completed.':work.run.status==='failed'?'The scenario exposed a failure.':'This device cannot execute the plan.'}</h2><p>{work.run.status==='success'?`The ${work.experience.task} flow produced ${work.run.output} in ${work.run.totalMs} simulated milliseconds.`:`The run stopped at ${work.run.trace.at(-1)?.stage}: ${work.run.trace.at(-1)?.message}`}</p></div><div><span>{work.run.trace.length}</span><small>TRACE SPANS</small></div><div><span>{work.run.totalMs}</span><small>SIMULATED MS</small></div><div><span>{assessment.score}</span><small>SIGNAL / 100</small></div><a className="button" href="#/benchmarks">Benchmark this setup →</a></section>}
  {work.run&&<RunPlayback key={JSON.stringify(work.run.config)+work.run.id} run={work.run}/>}
  {work.run?<TraceViewer run={work.run}/>:<section className="trace-empty"><span>AFTER YOU RUN</span><p>A trace will show input, processing, output, duration, route, metadata, and the exact failure point.</p></section>}
  <section className="scenario-picker" aria-labelledby="scenario-heading"><header><div><p className="eyebrow">SCENARIO LIBRARY</p><h2 id="scenario-heading">What should the twin encounter?</h2></div><p>Choose a story, then select its target in the virtual world. Each card changes real experience and simulator inputs.</p></header><div>{scenarios.map(s=><button aria-pressed={scenarioId===s.id} className={scenarioId===s.id?'active':''} onClick={()=>chooseScenario(s.id)} key={s.id}><span>{scenarioId===s.id?'SELECTED':'TRY'}</span><strong>{s.name}</strong><small>{s.description}</small></button>)}</div></section>
  <SimulationControls/>

  {work.runHistory.length>1&&<section className="run-history"><header><p className="eyebrow">RECENT RUNS</p><h2>Compare what your changes caused.</h2></header>{work.runHistory.map((item,index)=><div key={`${item.id}-${index}`}><span className={item.status}>{item.status}</span><strong>{item.config.fixture.replace('-',' ')} / {item.config.failureMode}</strong><small>{item.totalMs} ms · seed {item.seed}</small></div>)}</section>}
  <details className="lab-guide"><summary>New to Lens Lab? How the simulation works</summary>  <FeatureGuide title="From idea to evidence in three steps" intro="This is a deterministic simulator: identical settings and seed create the identical result. Its purpose is testing product logic and failure handling, not claiming physical-device performance." steps={[
   {number:'1',title:'Choose what the glasses should do',body:'Select a prepared experience or create your own in the Compiler.'},
   {number:'2',title:'Choose the world around it',body:'Apply a normal, denied-permission, degraded-network, low-battery, or offline scenario.'},
   {number:'3',title:'Run and inspect',body:'The optical output, outcome summary, and trace update from the same versioned artifact.'},
  ]}/>
</details>
  {aiOpen&&<section className="ai-drawer"><header><div><p className="eyebrow">REAL LOCAL SIGNAL</p><h2>Read an image without uploading it.</h2><p>For prototypers checking a real camera or image input. OCR runs in your browser and remains separate from simulated timing.</p></div><button aria-label="Close local OCR" className="icon-button" onClick={()=>setAiOpen(false)}>×</button></header><Suspense fallback={<p>Loading the OCR tool…</p>}><LocalAI/></Suspense></section>}
 </Page>;
}
