import {useEffect,useRef,useState,type ReactNode} from 'react';import {devices} from '../data/devices';import {routeLabels,type Route} from './router';
const help:Record<Route,{title:string;who:string;steps:string[]}>= {
 home:{title:'What is OpenLens?',who:'A browser-based workbench for people designing, researching, or developing smart-glasses experiences before every physical device is available.',steps:['Start in the Compiler if you have an idea in words.','Use Lens Lab to test normal and failure scenarios.','Compare hardware claims in Devices and inspect their sources in Research.']},
 lab:{title:'What is Lens Lab?',who:'A deterministic Digital Twin for product designers, QA teams, and developers testing how an experience behaves under changing conditions.',steps:['Choose an experience and scenario card.','Run it to produce a visible result or failure.','Inspect the canonical trace, then benchmark the same configuration.']},
 devices:{title:'What is Device Universe?',who:'A sourced comparison catalog for teams deciding which smart-glasses platform fits their requirements.',steps:['Search the eight current profiles.','Select up to three for a detailed matrix.','Treat maker API access and OpenLens adapter support as separate facts.']},
 compiler:{title:'What is the Compiler?',who:'A live planning tool for turning one supported product sentence into an explicit cross-device experience contract.',steps:['Type a translate, describe, caption, or reminder idea.','Review and correct the detected fields.','Save it to Lens Lab and test it immediately.']},
 benchmarks:{title:'What is Benchmark Lab?',who:'A reproducibility tool for developers comparing repeated simulated runs without hiding failures.',steps:['Choose how many trials to run.','Inspect the distribution and select any raw run.','Export JSON for replay or CSV for analysis.']},
 research:{title:'What is the Evidence Ledger?',who:'A source trail for researchers and builders checking where every device claim originated.',steps:['Open a device record.','Review each capability assertion and confidence.','Follow the manufacturer source or submit a correction.']},
 developers:{title:'What is Build with us?',who:'An adapter starter for developers connecting another hardware platform to OpenLens.',steps:['Name the target and select exposed capabilities.','Copy or download the generated TypeScript manifest.','Implement and physically verify it before claiming support.']},
 methodology:{title:'What is Methodology?',who:'The public definition of simulation, measurement, truth labels, statistics, replay, and known limits.',steps:['Check which label applies to a number.','Review how failed trials affect results.','Use artifact versions to reproduce a run.']},
 about:{title:'What is this project?',who:'An independent open-source effort by Shriyan Avadhanula to make wearable computing easier to inspect and build across.',steps:['Explore the public tools without an account.','Read the source and methodology.','Contribute evidence or an adapter through GitHub.']},
};
function Mark(){return <span className="brand-symbol" aria-hidden="true"><i/><i/></span>}
export function Shell({route,children}:{route:Route;children:ReactNode}){const [menu,setMenu]=useState(false);const [search,setSearch]=useState(false);const [helpOpen,setHelp]=useState(false);const searchRef=useRef<HTMLInputElement>(null);useEffect(()=>{document.title=`${routeLabels[route]} — OpenLens`;document.getElementById('main')?.focus();setHelp(false);const f=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setSearch(true)}if(e.key==='Escape'){setSearch(false);setMenu(false);setHelp(false)}};addEventListener('keydown',f);return()=>removeEventListener('keydown',f)},[route]);useEffect(()=>{if(search)searchRef.current?.focus()},[search]);const nav=(keys:Route[])=>keys.map(key=><a className={route===key?'active':''} href={key==='home'?'#/':`#/${key}`} onClick={()=>setMenu(false)} key={key}>{routeLabels[key]}</a>);return <><a className="skip-link" href="#main">Skip cinematic</a><header className="site-header"><a className="brand" href="#/" aria-label="OpenLens home"><Mark/>OPENLENS</a><nav className="desktop-nav" aria-label="Primary">{nav(['lab','devices','compiler','benchmarks','research'])}</nav><div className="header-actions"><button className="help-button" onClick={()=>setHelp(true)}>What is this?</button><button className="search-button" onClick={()=>setSearch(true)}><span>Search</span><kbd>⌘ K</kbd></button><a className="header-cta" href="#/developers">Build with us</a><button className="menu-toggle" aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?'Close':'Menu'}</button></div></header>{menu&&<nav className="mobile-nav" aria-label="Mobile navigation">{nav(['home','lab','devices','compiler','benchmarks','research','developers','methodology','about'])}</nav>}{children}<Footer/>{search&&<Search close={()=>setSearch(false)} inputRef={searchRef}/>} {helpOpen&&<Help route={route} close={()=>setHelp(false)}/>}</>}
function Help({route,close}:{route:Route;close:()=>void}){const content=help[route];return <aside className="help-drawer" role="dialog" aria-modal="true" aria-labelledby="help-title"><header><div><p className="eyebrow">PLAIN-LANGUAGE GUIDE</p><h2 id="help-title">{content.title}</h2></div><button className="icon-button" onClick={close} aria-label="Close guide">×</button></header><p>{content.who}</p><ol>{content.steps.map(step=><li key={step}>{step}</li>)}</ol><button className="button primary full" onClick={close}>Start using this feature</button></aside>}
function Search({close,inputRef}:{close:()=>void;inputRef:React.RefObject<HTMLInputElement|null>}){const [q,setQ]=useState('');const entries=[...Object.entries(routeLabels).map(([key,label])=>({href:key==='home'?'#/':`#/${key}`,title:label,meta:'Section'})),...devices.map(d=>({href:`#/devices?device=${d.id}`,title:d.name,meta:`${d.manufacturer} · ${d.integrationStatus}`}))].filter(item=>`${item.title} ${item.meta}`.toLowerCase().includes(q.toLowerCase()));return <div className="overlay" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><div className="search-dialog" role="dialog" aria-modal="true" aria-labelledby="search-title"><header><div><p className="eyebrow">UNIVERSAL SEARCH</p><h2 id="search-title">Find a system.</h2></div><button className="icon-button" onClick={close} aria-label="Close search">×</button></header><input ref={inputRef} className="search-input" placeholder="Devices, tools, evidence, methodology…" value={q} onChange={e=>setQ(e.target.value)}/><div className="search-results">{entries.map(item=><a href={item.href} onClick={close} key={item.href}><span>{item.title}</span><small>{item.meta}</small></a>)}</div></div></div>}
function Footer(){return <footer className="site-footer"><div><a className="brand" href="#/"><Mark/>OPENLENS</a><p>One open optical layer for hardware, experiences, traces, evidence, and measurement.</p></div><div className="footer-nav"><a href="#/lab">Lens Lab</a><a href="#/devices">Devices</a><a href="#/research">Evidence</a><a href="#/methodology">Methodology</a><a href="#/about">About</a></div><div className="footer-meta"><span>v0.2.0 / PUBLIC PREVIEW</span><span>SIMULATION IS NEVER PRESENTED AS HARDWARE MEASUREMENT.</span></div></footer>}
