import {useMemo,useState} from 'react';
import {planAIRoute,type AIRouteRequest,type AITask} from '../core';

const tasks:Array<{id:AITask;label:string}>=[{id:'ocr',label:'Read text (OCR)'},{id:'translation',label:'Translate a sign'},{id:'scene-understanding',label:'Understand a scene'},{id:'object-identification',label:'Identify an object'},{id:'captioning',label:'Caption speech'},{id:'speech-output',label:'Speak output'}];

export default function AIRouterLab({localVoice}:{localVoice:boolean}){
 const [request,setRequest]=useState<AIRouteRequest>({task:'ocr',privacy:'local-only',priority:'latency',cost:'zero-only'});
 const decision=useMemo(()=>planAIRoute(request,{localOcr:typeof Worker!=='undefined'&&typeof WebAssembly!=='undefined',localVoice,browserSpeechRecognition:'SpeechRecognition'in window||'webkitSpeechRecognition'in window,webGpu:'gpu'in navigator,localVisionModel:false,advancedProvider:false}),[request,localVoice]);
 const update=<K extends keyof AIRouteRequest>(key:K,value:AIRouteRequest[K])=>setRequest(current=>({...current,[key]:value}));
 return <section className="ai-router" aria-labelledby="ai-router-title"><header><div><p className="eyebrow">OPENLENS AI ROUTER / LIVE CAPABILITY DECISION</p><h3 id="ai-router-title">Choose the route the browser can defend.</h3></div><span className={decision.status}>{decision.status}</span></header><div className="router-controls"><label>Task<select value={request.task} onChange={event=>update('task',event.target.value as AITask)}>{tasks.map(task=><option key={task.id} value={task.id}>{task.label}</option>)}</select></label><label>Privacy<select value={request.privacy} onChange={event=>update('privacy',event.target.value as AIRouteRequest['privacy'])}><option value="local-only">Local only</option><option value="provider-allowed">Provider allowed</option></select></label><label>Priority<select value={request.priority} onChange={event=>update('priority',event.target.value as AIRouteRequest['priority'])}><option value="latency">Lowest latency</option><option value="quality">Highest quality</option></select></label><label>Cost<select value={request.cost} onChange={event=>update('cost',event.target.value as AIRouteRequest['cost'])}><option value="zero-only">Zero cost only</option><option value="paid-allowed">Paid allowed</option></select></label></div><div className="route-verdict" aria-live="polite"><div><span>SELECTED ROUTE</span><strong>{decision.route}</strong><small>{decision.provider}</small></div><p>{decision.reason}</p></div>{decision.stages.length>0&&<div className="router-stages" aria-label="Selected AI pipeline">{decision.stages.map((stage,index)=><div key={stage}><span>{(index+1).toString().padStart(2,'0')}</span><strong>{stage}</strong>{index<decision.stages.length-1&&<i aria-hidden="true">→</i>}</div>)}</div>}<p className="router-disclosure">{decision.disclosure}</p></section>;
}
