import {useEffect,useRef,useState,type KeyboardEvent as ReactKeyboardEvent} from 'react';

const paths={
 explore:{label:'I’m curious',title:'Try smart glasses without owning a pair.',body:'Enter the virtual park, focus the French sign, and watch the selected glasses route the result.',steps:['Open the first-person park','Select SORTIE to run translation','Change the device or environment'],route:'lab',action:'Enter the virtual park'},
 build:{label:'I want to build',title:'Turn an idea into an inspectable plan.',body:'Write one supported behavior, review its routes across every profile, then run it in the Optical Twin.',steps:['Describe the experience','Review the detected contract','Run a compatible device model'],route:'compiler',action:'Open the Experience Compiler'},
 compare:{label:'I’m choosing glasses',title:'Find the hardware boundary that matters.',body:'Switch among physical, developer-access, and OpenLens layers before comparing the finalists.',steps:['Scan the capability matrix','Mark required features','Open Device Doctor on a finalist'],route:'devices',action:'Compare the device field'},
 verify:{label:'I need evidence',title:'Follow every claim back to its source.',body:'Search the ledger, inspect conflicts and unknowns, then keep simulated results separate from hardware evidence.',steps:['Search a device or capability','Open the claim and source record','Inspect benchmark methodology'],route:'research',action:'Open the evidence ledger'},
} as const;
type PathId=keyof typeof paths;
const tour=[
 {title:'Explore the field.',body:'Meet seven sourced physical profiles and the OpenLens reference twin.',route:'devices',action:'Open Device Universe'},
 {title:'Choose a target.',body:'Mark the capabilities your idea requires and let Device Fit explain each match and blocker.',route:'devices',action:'Find a device'},
 {title:'See the boundary.',body:'Switch among physical hardware, maker developer access, and code OpenLens can execute now.',route:'devices',action:'Open the capability matrix'},
 {title:'Enter the virtual park.',body:'Aim at a sign or speaker, change the environment, and run a documented-capability model.',route:'lab',action:'Enter Lens Lab'},
 {title:'Use a real local signal.',body:'Open the OCR drawer to read a demo, uploaded image, or camera frame entirely in the browser.',route:'lab',action:'Try local OCR'},
 {title:'Measure repeated runs.',body:'Run seeded trials, keep every failure, select a raw result, and export its evidence.',route:'benchmarks',action:'Open Benchmark Lab'},
 {title:'Compare the candidates.',body:'Place up to three profiles side by side and keep unknown or conflicting claims visible.',route:'devices',action:'Compare devices'},
 {title:'Build the open layer.',body:'Generate a typed adapter, contract test, guide, and explicit hardware-verification record.',route:'developers',action:'Build an adapter'},
] as const;

export default function VisitorPathfinder(){
 const [active,setActive]=useState<PathId>('explore');const [tourOpen,setTourOpen]=useState(false);const path=paths[active];
 return <section className="visitor-pathfinder" aria-labelledby="pathfinder-title"><aside><p className="eyebrow" style={{color:'#4b5655'}}>START WITH YOUR QUESTION</p><h2 id="pathfinder-title">Choose a way<br/>into OpenLens.</h2><p>Every path starts with something you can use now.</p><div className="path-options">{(Object.entries(paths) as [PathId,typeof paths[PathId]][]).map(([id,item],index)=><button onClick={()=>setActive(id)} aria-pressed={active===id} key={id}><span style={{color:'#4f5957'}}>0{index+1}</span><strong>{item.label}</strong><i>↗</i></button>)}</div><button className="button" type="button" style={{marginTop:24,color:'#1d2526',borderColor:'#596361'}} onClick={()=>setTourOpen(true)}>Take the 2-minute tour →</button></aside><div className={`path-map path-${active}`} aria-live="polite"><header><span>YOUR ROUTE / {active.toUpperCase()}</span><small>3 STEPS · NO ACCOUNT</small></header><div><p className="eyebrow">RECOMMENDED PATH</p><h3>{path.title}</h3><p>{path.body}</p><ol>{path.steps.map((step,index)=><li key={step}><span>0{index+1}</span><strong>{step}</strong></li>)}</ol><a className="button primary" href={`#/${path.route}`}>{path.action} ↗</a></div><div className="path-optic" aria-hidden="true"><i/><i/><i/><span>{active.toUpperCase()}</span></div></div>{tourOpen&&<FirstVisitTour close={()=>setTourOpen(false)}/>}</section>;
}

function FirstVisitTour({close}:{close:()=>void}){
 const [step,setStep]=useState(0);const drawer=useRef<HTMLElement>(null);const item=tour[step];
 useEffect(()=>{const previous=document.activeElement as HTMLElement|null;const overflow=document.body.style.overflow;const escape=(event:KeyboardEvent)=>{if(event.key==='Escape')close()};document.body.style.overflow='hidden';drawer.current?.querySelector('button')?.focus();addEventListener('keydown',escape);return()=>{document.body.style.overflow=overflow;removeEventListener('keydown',escape);if(previous?.isConnected)previous.focus()}},[]);
 const trap=(event:ReactKeyboardEvent<HTMLElement>)=>{if(event.key!=='Tab')return;const focusable=Array.from(drawer.current?.querySelectorAll<HTMLElement>('button:not([disabled]),a[href]')??[]);const first=focusable[0],last=focusable.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus()}};
 return <aside ref={drawer} className="help-drawer" role="dialog" aria-modal="true" aria-labelledby="tour-title" onKeyDown={trap}><header><div><p className="eyebrow">GUIDED TOUR · {step+1} / {tour.length}</p><h2 id="tour-title" style={{color:'#edf0eb'}}>{item.title}</h2></div><button className="icon-button" type="button" onClick={close} aria-label="Close tour">×</button></header><p style={{color:'#aeb7b8'}}>{item.body}</p><ol><li>Every step opens a working, account-free OpenLens surface.</li></ol><div className="button-row"><button className="button" type="button" disabled={step===0} onClick={()=>setStep(value=>value-1)}>Previous</button>{step<tour.length-1?<button className="button primary" type="button" onClick={()=>setStep(value=>value+1)}>Next step</button>:<a className="button primary" href="#/lab">Enter OpenLens</a>}</div><a className="text-link" style={{color:'#d6fbff'}} href={`#/${item.route}`}>{item.action} ↗</a></aside>;
}
