import {capabilityKeys,type Capability} from './types';

export interface AdapterStarterInput {deviceName:string;deviceId:string;capabilities:Capability[]}
export interface AdapterStarterFile {path:string;language:'typescript'|'json'|'markdown';content:string}

const idPattern=/^[a-z0-9]+(?:-[a-z0-9]+)*$/;
const className=(name:string)=>{
 const value=name.split(/[^a-zA-Z0-9]+/).filter(Boolean).map(part=>part[0].toUpperCase()+part.slice(1)).join('')||'Device';
 return `${/^\d/.test(value)?'Device':''}${value}Adapter`;
};
const literal=(value:string)=>JSON.stringify(value);

export function validateAdapterStarter(input:AdapterStarterInput){
 const errors:string[]=[];
 if(!input.deviceName.trim())errors.push('Enter a device name.');
 if(!idPattern.test(input.deviceId))errors.push('Use a stable lowercase ID with letters, numbers and single hyphens.');
 if(input.capabilities.length===0)errors.push('Select at least one capability.');
 if(input.capabilities.some(capability=>!capabilityKeys.includes(capability)))errors.push('The capability list contains an unsupported value.');
 return errors;
}

export function buildAdapterStarter(input:AdapterStarterInput):AdapterStarterFile[]{
 const errors=validateAdapterStarter(input);if(errors.length)throw new Error(errors.join(' '));
 const adapterClass=className(input.deviceName);
 const adapterPath=`src/adapters/${input.deviceId}.ts`;
 const capabilities=input.capabilities.map(capability=>literal(capability)).join(', ');
 const source=`import type { AdapterManifest, CompiledPlan, DeviceAdapter, RunResult, SimulationConfig } from '../core';

export const manifest = {
  id: ${literal(`${input.deviceId}-adapter`)},
  deviceId: ${literal(input.deviceId)},
  name: ${literal(`${input.deviceName.trim()} adapter`)},
  status: 'unavailable',
  mode: 'hardware',
  capabilities: [${capabilities}],
  disclosure: 'Transport scaffold generated by OpenLens. No hardware verification has been recorded.'
} satisfies AdapterManifest;

/** Implement this boundary with the vendor SDK or a documented local bridge. */
export interface VendorTransport {
  connect(): Promise<void>;
  disconnect(): Promise<void>;
  execute(request: {plan: CompiledPlan; config: SimulationConfig}): Promise<RunResult>;
}

export class ${adapterClass} implements DeviceAdapter {
  readonly manifest = manifest;
  #connected = false;

  constructor(private readonly transport: VendorTransport) {}

  get connected() { return this.#connected; }

  async connect() {
    if (this.#connected) return;
    await this.transport.connect();
    this.#connected = true;
  }

  async disconnect() {
    if (!this.#connected) return;
    await this.transport.disconnect();
    this.#connected = false;
  }

  async execute(plan: CompiledPlan, config: SimulationConfig) {
    if (!this.#connected) throw new Error('Adapter is not connected.');
    if (plan.deviceId !== manifest.deviceId) throw new Error('Plan device does not match adapter.');
    const unsupported = plan.steps.flatMap(step => step.capability && !manifest.capabilities.includes(step.capability) ? [step.capability] : []);
    if (unsupported.length) throw new Error(\`Plan requires unsupported capabilities: \${[...new Set(unsupported)].join(', ')}.\`);
    return this.transport.execute({plan, config});
  }
}
`;
 const test=`import {describe,expect,it,vi} from 'vitest';
import type {CompiledPlan,RunResult,SimulationConfig} from '../core';
import {${adapterClass},manifest} from './${input.deviceId}';

const plan={deviceId:manifest.deviceId,steps:[]} as unknown as CompiledPlan;
const config={} as SimulationConfig;
const result={} as RunResult;

describe('${adapterClass}',()=>{
  it('enforces connection and delegates a matching plan',async()=>{
    const transport={connect:vi.fn(),disconnect:vi.fn(),execute:vi.fn(async()=>result)};
    const adapter=new ${adapterClass}(transport);
    await expect(adapter.execute(plan,config)).rejects.toThrow('not connected');
    await adapter.connect();
    await expect(adapter.execute(plan,config)).resolves.toBe(result);
    expect(transport.execute).toHaveBeenCalledWith({plan,config});
    await adapter.disconnect();
    expect(adapter.connected).toBe(false);
  });

  it('rejects a plan for another device',async()=>{
    const adapter=new ${adapterClass}({connect:vi.fn(),disconnect:vi.fn(),execute:vi.fn()});
    await adapter.connect();
    await expect(adapter.execute({...plan,deviceId:'another-device'},config)).rejects.toThrow('does not match');
  });
});
`;
 const verification=JSON.stringify({schemaVersion:1,adapterId:`${input.deviceId}-adapter`,status:'unverified',device:{name:input.deviceName.trim(),firmware:null,serialRedacted:true},environment:{host:null,browserOrRuntime:null,vendorSdk:null},observedAt:null,tester:null,cases:[{name:'connect-disconnect',result:'not-run',notes:''},{name:'permission-denied',result:'not-run',notes:''},{name:'transport-loss',result:'not-run',notes:''},{name:'unsupported-capability',result:'not-run',notes:''}],rawEvidence:[],disclosure:'Do not set verified-hardware until these cases have reproducible observations on the named physical device.'},null,2)+'\n';
 const example=`import {compileExperience, defaultSimulationConfig, DigitalTwinAdapter, experiencePresets, getDevice} from '../core';
import {createOpenLens} from '../sdk';

/** Run with the reference twin before implementing a vendor transport. */
export async function runOpenLensSDKExample() {
  const device = getDevice('openlens-twin');
  const plan = compileExperience(experiencePresets[0], device);
  const openlens = createOpenLens(new DigitalTwinAdapter(device));
  await openlens.device.connect();
  try {
    return await openlens.device.execute(plan, defaultSimulationConfig);
  } finally {
    await openlens.device.disconnect();
  }
}
`;
 const readme=`# ${input.deviceName.trim()} adapter starter

Generated by OpenLens. This bundle creates a typed lifecycle and test boundary; it does not claim a working hardware connection.

1. Copy \`${adapterPath}\` and its test into the matching repository folders.
2. Implement \`VendorTransport\` with the official SDK or a documented local bridge.
3. Run \`src/examples/openlens-sdk-example.ts\` through a test or local entrypoint to verify the SDK lifecycle against the deterministic reference twin.
4. Run \`npm test\`, then add denied-permission, timeout, disconnect and malformed-response cases.
5. Complete \`verification-record.json\` on the physical device and retain raw observations.
6. Change the manifest to \`implemented-untested\` only when transport code exists. Use \`verified-hardware\` only after the record is complete and reproducible.
7. Register the manifest in \`src/adapters/registry.ts\` after review.

Selected capabilities: ${input.capabilities.join(', ')}.
`;
 return[
  {path:adapterPath,language:'typescript',content:source},
  {path:`src/adapters/${input.deviceId}.test.ts`,language:'typescript',content:test},
  {path:'src/examples/openlens-sdk-example.ts',language:'typescript',content:example},
  {path:'verification-record.json',language:'json',content:verification},
  {path:'README.md',language:'markdown',content:readme},
 ];
}
