import React from 'react';
import { createRoot } from 'react-dom/client';
import App from './App';
import './styles.css';
import './mobile.css';
import './dark-overrides.css';
import './readability.css';
import './flagship.css';
import './a11y-hotfix.css';
import './resilience.css';
import './scenario-capsule.css';
import './workbench-polish.css';
import './environment.css';
import './optical-studio.css';
import './instrument-workspace.css';
import './author-evidence.css';
import './evidence-builder.css';
import './editorial-pages.css';
import './home-atlas.css';
import './virtual-world.css';
import './motion-system.css';
import './motion-audit-fixes.css';
createRoot(document.getElementById('root')!).render(<React.StrictMode><App /></React.StrictMode>);
