import React from 'react';
import { createRoot } from 'react-dom/client';
import App from './App';
import './styles.css';
import './mobile.css';
import './dark-overrides.css';
import './readability.css';
import './flagship.css';
import './a11y-hotfix.css';
import './resilience.css';
createRoot(document.getElementById('root')!).render(<React.StrictMode><App /></React.StrictMode>);
